* cloudera CDH
** download the virtualbox imate
#+BEGIN_SRC 
wget https://downloads.cloudera.com/demo_vm/virtualbox/cloudera-quickstart-vm-5.13.0-0-virtualbox.zip

#+END_SRC
** download and start docker image

#+BEGIN_SRC 
docker pull cloudera/quickstart:latest
docker run --hostname=quickstart.cloudera --privileged=true -t -i -d -p 8888:8888 -p 8099:80 -p 7180:7180 cloudera/quickstart:latest /usr/bin/docker-quickstart
docker exec -i -t -d  <containerid> /home/cloudera/cloudera-manager --express --force

#to start cloudera manager
/home/cloudera/cloudera-manager --express --force
#+END_SRC
** upgrading cdh

Install the parcels

Remote parcels repo url: https://archive.cloudera.com/cdh5/latest

Here are the packages if u want to download latest cdh:
https://archive.cloudera.com/cm5/redhat/7/x86_64/cm/

For rhel6
https://archive.cloudera.com/cm5/redhat/6/x86_64/cm/

#+BEGIN_SRC 
service cloudera-scm-server stop
service cloudera-scm-agent stop

ls /etc/yum.repos.d/
cat /etc/yum.repos.d/cloudera-manager.repo

#update the cloudera manager version and location of archive from web
vi /etc/yum.repos.d/cloudera-manager.repo

yum -y upgrade cloudera-manager-server cloudera-manager-servers cloudera-manager-agent

service cloudera-scm-server start
service cloudera-scm-agent start
#+END_SRC

- Go to cloudera manager ui, upgrade CDH, parcels will be downloaded 
- Go to CDM about - see the latest

** Spark 2 runs on JDK 8 , must upgrade jdk8, CDH 5.3 onw supports jdk 8

Remember this goes to director:

Get the link from https://archive.cloudera.com/director/redhat/7/x86_64/director/

For centos 6
https://archive.cloudera.com/director/redhat/6/x86_64/director/

#+BEGIN_SRC 
service cloudera-scm-server stop
service cloudera-scm-agent stop

rpm -ivh https://archive.cloudera.com/director/redhat/6/x86_64/director/2.8.0/RPMS/x86_64/oracle-j2sdk1.8-1.8.0+update121-1.x86_64.rpm

vi /etc/default/cloudera-scm-server
# add at the end of file:   export JAVA_HOME=/usr/java/latest

# find the latest java in /usr/java
ls /usr/java

#add the symbolic link to the latest java
ln -s /usr/java/latest  jdk1.8.0_121-cloudera

# find and remove old jdk
yum list oracle*

yum remove -y oracle-j2sdk1.7.x86_64

#set the java in bash shell
vi /etc/profile.d/java.sh
# add at the end of file:   export JAVA_HOME=/usr/java/latest

service cloudera-scm-server stop
service cloudera-scm-agent stop


/home/cloudera/cloudera-manager --express --force
#+END_SRC

You need to jdk in all the nodes so go from the web console fo cdm

Go to web UI 
hosts > configuration > look for java home

** if you encounter zookeeper doesn't start because unable to access data directory
#+BEGIN_SRC 
mkdir -p /var/lib/zookeeper/logs/version-2
chown -R zookeeper:zookeeper /var/lib/zookeeper

#or if it is /data
mkdir -p /data/zookeeper/logs/version-2
chown -R zookeeper:zookeeper /data/zookeeper
#+END_SRC

** if hdfs is in safe mode unable to start

#+BEGIN_SRC 
sudo -u hdfs hdfs dfsadmin -safemode leave
#+END_SRC

** yarn /var/lib/hadoop-yarn/yarn-nm-recovery/yarn-nm-state/LOCK permission denied

#+BEGIN_SRC 
chown -R yarn:yarn /var/lib/hadoop-yarn
#+END_SRC

** HDFS httpFS

#+BEGIN_SRC 
curl "http://<httpFS server dns>:14000/webhdfs/v1/?op=LISTSTATUS&user.name=hdfs"

curl "http://<httpFS server dns>:14000/webhdfs/v1/?user.name=hdfs&op=LISTSTATUS"

curl -X PUT "http://<httpFS server dns>:14000/webhdfs/v1/httpFSTest?user.name=hdfs&op=MKDIRS"

curl -i -X PUT "http://<httpFS server dns>:14000/webhdfs/v1/muthu4allhttpFS.txt?user.name=hdfs&op=CREATE"

curl -i -H 'Content-Type: application/octet-stream' -T test.txt "http://<httpFS server dns>:14000/webhdfs/v1/muthu4allhttpFS.txt?op=CREATE&user.name=hdfs&data=true"

#+END_SRC

* Cloudera
  
** Analytics
1. Descriptive
   1. What happened ? - PAST
   2. Descriptive Statistics
   3. Data Clustering
2. Diagnostic
   1. Why did it happen? / Why is it happening?
   2. Sensitivity Analysis
3. Predictive
   1. What will happen?
   2. Linear and Logistic Regression
4. Prescriptive
   1. What should I do? What should happen?
   2. Simulation
   3. Non Linear Programming
** cloudera manager arch
*** Cloudera manager
**** Mgmt Service
**** Agent
**** JDK
**** Cloudera Manager Database
**** Repository - Packages & Parcels
*** Cluster Host(s)
**** Agent
**** JDK
**** CDH
** Cloudera installation phases and paths
*** Pre requisites
1. disable SELinux

#+BEGIN_SRC
cat /etc/selinux/config
sed -i 's/SELINUX=enforcing/SELINUX=disabled/' /etc/selinux/config

cat /etc/sysconfig/selinux
sed -i 's/SELINUX=enforcing/SELINUX=disabled/' /etc/sysconfig/selinux

#+END_SRC


2. TurnOff iptables

#+BEGIN_SRC 
service iptables stop
chkconfig iptables off
#+END_SRC

3. Change swappiness

#+BEGIN_SRC 

cat /sys/kernel/mm/transparent_hugepage/enabled


vi /etc/systemd/system/disable-thp.service

#+END_SRC

#+BEGIN_SRC 
#/etc/systemd/system/disable-thp.service
[Unit]
Description=Disable Transparent Huge Pages (THP)

[Service]
Type=simple
ExecStart=/bin/sh -c "echo 'never' > /sys/kernel/mm/transparent_hugepage/enabled && echo 'never' > /sys/kernel/mm/transparent_hugepage/defrag"

[Install]
WantedBy=multi-user.target

#+END_SRC

#+BEGIN_SRC 
sudo systemctl daemon-reload
sudo systemctl start disable-thp
sudo systemctl enable disable-thp

#+END_SRC


#+BEGIN_SRC 
cat /proc/sys/vm/swappiness

echo "vm.swappiness = 1" >> /etc/sysctl.conf
cat /etc/sysctl.conf

#+END_SRC

4. Resize volume

#+BEGIN_SRC 
df -u
#list the block devices
lsblk

#find out which partition need to grow on which disk

#then grow the partition number to resized value
sudo growpart /dev/xvdf 1

#extend the filesystem to new volume capacity

sudo resize2fs /dev/xvda1

#if it is xfs
sudo yum install xfsprogs
sudo xfs_growfs -d /mnt

sudo file -s /dev/xvd*

#+END_SRC

5. Install ntp

#+BEGIN_SRC 
sudo yum -y update
sudo yum -y instal ntp
chkconfig ntpd on

#+END_SRC

#+BEGIN_SRC 
yum install -y httpd

chkconfig httpd on

# archive ===>http://archive.cloudera.com/cm5/repo-as-tarball/5.14.1/

wget  http://archive.cloudera.com/cm5/repo-as-tarball/5.15.2/cm5.15.2-centos7.tar.gz

sudo tar zxvf cm5.15.2-centos7.tar.gz  -C /var/www/html

# get the parcels
mkdir -p /var/www/html/cdh5.14.0
cd /var/www/html/cdh5.14.0
wget http://archive.cloudera.com/cdh5/parcels/5.15.1/CDH-5.15.1-1.cdh5.15.1.p0.4-el7.parcel
wget http://archive.cloudera.com/cdh5/parcels/5.15.1/manifest.json

#+END_SRC
*** sample starter commands 
#+BEGIN_SRC 
vi /etc/selinux/config
service iptables status
service iptables stop
yum install iptables-services
service iptables status
service iptables disable
chkconfig iptables off
df -h
resize2fs /dev/xvda1
fdisk /dev/xvda
ls /
xfs_growfs /dev/root_vg/root
xfs_growfs /dev/xvda1/root
xfs_growfs /dev/xvda1
xfs_growfs /dev/xvda1/
df -h
echo "vm.swappiness=1" >> /etc/syctl.conf
vi /etc/sysctl.conf
vi /etc/sysctl.conf
echo "vm.swappiness=1" >> /etc/syctl.conf
vi /etc/sysctl.conf
vi /etc/sysctl.conf
cd /etc/sysctl.d/
ls
vi 99-sysctl.conf
reboot
history > hist.sh

#+END_SRC

*** steps/phases
1. Install JDK

2. Setup Database

3. Install Cloudera Manager Server

4. Install Cloudera Manager Agents

5. Install CDH nd Managed Service softwares

6. Create, Configure and Start CDH and Managed Services

** create the tf template spin up cluster
** create the ansible playbook for base
*** disable selinux
*** turn off iptables
*** resize volume
*** change swappiness
** Path B via packages

** Ldap
yum install slapd



slappasswd 

use this password to update the following file:
vi /etc/openldap/slapd.conf

change the olcRootPW

#+BEGIN_SRC 
ldapmodify -Q -Y EXTERNAL -H ldapi:/// << E0F
dn: olcDatabase={2}hdb,cn=config
changetype: modify
add: olcRootPW
olcRootPW: {SSHA}qUoTRPwppaedqHQTgYOPYWokr3SiXjbK
E0F

#+END_SRC
