- hosts: localhost
  connection: local
  vars:
    s3_bucket_name: mybucket-repo
    project_id: auth-api
  tasks:
    - name: "list all jars in s3 bucket"
      shell: "aws s3 ls --recursive s3://{{s3_bucket_name}}/{{project_id}} | grep '.*\\.jar$' | awk -F \" \" '{print $4}'"
      register: resp
    - debug: var=resp

    - name: "list the latest jar in s3 bucket"
      shell: "aws s3 ls s3://{{s3_bucket_name}}/{{project_id}}/ --recursive | sort | tail -n 1 | awk -F \" \" '{print $4}'"
      register: resp
    - debug: var=resp