* Checklist
** Quick action checklist
- Sit totally relaxed
- Eyes relaxed & wide open
- forehead relaxed
- Feel the mind
- Fixed gaze.

** Checklist
- Smooth sweep eyes
- Look for action words. Create mental image.
- Clearly see, feel the thought in mind's eye.
- Mark action works
- Point blank eye sweep. Not targetting words. Just the thought.
- Feet fixed and flat on ground. Energy grounded.

* 4 step process:-

Start with a comfortable and straight posture. Reading a new material is an active sport (revision can be passive sport also.).  Sit still, calm, take a deep breath, smile and concentrate.

** 4 Phase process of Reading:- 
- 1. Scaffolding: Get a clear High Level Overview/Helicopter View - the complete flow of the material. 
- 2. Skimming: Fast fluid eye movements through content. Quick overview/Overall thought process of the material. Switch back & forth between high-level view and content of material. Feel the thought process. Filling in Helicopter view. Understanding of new terms. 
- 3. Deep diving: Thorough read each sentence - pause and understand the thought clearly.  Mark action words/keywords. Create mind map of keywords - connect the thoughts. Switch back & forth between high-level view & content. 
- 4. Tip-tapping - tap, tap, tap the keywords - invoke the thoughts and Go!
